# -*- coding: utf-8 -*-
"""[booking] scraping dati generali e recensioni

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VeBUFWzptyCav9-LR4ROhB9ILHoS1MUI
"""

import requests # libreria per generare richieste HTTP 
from bs4 import BeautifulSoup as bs # libreria per scraping
import pandas as pd
import json
import math

def addTimeFilters(target_str_ ,checkin_, checkout_):

  target_str = str(target_str_)
  checkin_date = str(checkin_)
  checkout_date = str(checkout_)
  
  links_with_dates = f'{target_str}?checkin={checkin_date};checkout={checkout_date};selected_currency=EUR'

  return links_with_dates

# conversione a stringa e trimming dei link
def editLinks(all_soup_href, checkin_, checkout_):

  edited_links = []
  i = 0
  while i < len(all_soup_href):
    edited_links.append(str(all_soup_href[i])) # converte i link da tipo bs4 in tipo stringa e li mette in edited_links
    edited_links[i] = edited_links[i][53:] # trimma i primi 53 caratteri
    edited_links[i] = edited_links[i].partition("?")[0] # separa in base al "?" e seleziona tutti i caratteri prima di "?"
    edited_links[i] = addTimeFilters(edited_links[i], checkin_, checkout_) # aggiunge le date
    i += 1

  return edited_links

def editLinksReviews(all_soup_href):

  edited_links_reviews = []
  i = 0
  while i < len(all_soup_href):
    edited_links_reviews.append(str(all_soup_href[i])) # converte i link da tipo bs4 in tipo stringa e li mette in edited_links
    edited_links_reviews[i] = edited_links_reviews[i][53:] # trimma i primi 53 caratteri
    edited_links_reviews[i] = edited_links_reviews[i].partition("?")[0] # separa in base al "?" e seleziona tutti i caratteri prima di "?"

    edited_links_reviews[i] = edited_links_reviews[i].replace("hotel/it", "reviews/it/hotel")
    edited_links_reviews[i] = edited_links_reviews[i] + "?r_lang=it&customer_type=total&order=completed_desc&hp_nav=0&old_page=0&order=featuredreviews&r_lang=it&rows=24&page=1"

    i += 1

  return edited_links_reviews

# prendi il numero delle pagine di recensioni
# lo ottiene facendo numero recensioni/24
# 24 è il numero di recensioni per pagina
# il risultato viene arrotondato per eccesso

def getReviewsPage(soup):

  n_reviews_page = 0

  p_reviews = soup.find("p", {"class": "review_list_score_count"})
  if p_reviews is not None: p_reviews = p_reviews.text
  else: return n_reviews_page

  tot_reviews = [int(s) for s in p_reviews.split() if s.isdigit()][0]
  n_reviews_page = int(math.ceil(tot_reviews/24))

  return n_reviews_page

# modifica l'url per prendere le varie pagine delle recensioni
# restituisce una lista con gli url modificati per accedere a tutte le recensioni di un camping

def getReviewsUrl(url, n_reviews_page):

  url_reviews = []
  page = 1

  for i in range(n_reviews_page):
    
    url = url[:-1]
    url = url + str(page)
    url_reviews.append(url)

    page += 1

  return url_reviews

# prende i dati delle recensioni e ritorna una lista
def getReviewsData(soup, url):

  all_reviews = []

  reviews_list = soup.find_all("div", {"class": "review_item_review"}) # tutti i div delle recensioni
  for review in reviews_list:

    review_appoggio = []

    review_vote = review.find("div", {"class": "review_item_header_score_container"})
    review_appoggio.append(review_vote.text.strip())
    
    review_title = review.find("span", {"itemprop": "name"})
    review_appoggio.append(review_title.text.strip())

    neg_review = review.find("p", {"class": "review_neg"})
    if neg_review is not None: review_appoggio.append(neg_review.text.strip())
    else: review_appoggio.append("no negative review")
    
    pos_review = review.find("p", {"class": "review_pos"})
    if pos_review is not None: review_appoggio.append(pos_review.text.strip())
    else: review_appoggio.append("no positive review")

    staydate_review = review.find("p", {"class": "review_staydate"})
    review_appoggio.append(staydate_review.text.strip())

    url_ = (str(url).partition("?")[0])
    review_appoggio.append(url_)

    all_reviews.append(review_appoggio)

  return all_reviews


url = "https://www.booking.com/searchresults.it.html?ss=Marche%2C+Italia&is_ski_area=&checkin_year=&checkin_month=&checkout_year=&checkout_month=&group_adults=2&group_children=0&no_rooms=1&b_h4u_keep_filters=&from_sf=1&dest_id=905&dest_type=region&search_selected=true&nflt=ht_id%3D224%3Bht_id%3D214"
head = {'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:100.0) Gecko/20100101 Firefox/100.0'}
response_links = requests.get(url, headers = head)
soup_links = bs(response_links.text, 'lxml')

all_links = soup_links.find_all("a", {"data-testid": "title-link"}) # prendo tutti i link href dei vari camping presenti

links_with_dates = editLinks(all_links, "", "") # link editati per fare scraping dei DATI dei camping
links_for_reviews = editLinksReviews(all_links) # link editati per fare scraping delle RECENSIONI


"""** SCRAPINGDATI GENERALI**"""

camping_general_data = []

# DATI GENERALI =============================================================================================================================
for l in links_with_dates:

  print("scraping generali: " + l)
  camping = []

  response = requests.get(l, headers = head)
  soup_general_data = bs(response.text, 'lxml')

  # nome, descrizione, ecc... ===============================================================================================================
  camping_data_raw = soup_general_data.find("script", {"type": "application/ld+json"}) # assolutamente da aggiustare application/ld+json e prendere una cosa più specifica
  data_camping_json = json.loads(camping_data_raw.string)

  camping.append(data_camping_json['name'])
  camping.append(data_camping_json['address']['streetAddress'])

  camping_description = soup_general_data.find("div", {"id": "property_description_content"})
  if camping_description is not None: camping.append(camping_description.text.strip())
  else: camping.append("No camping description")

  camping_host_description = soup_general_data.find("div", {"class": "db29ecfbe2 ca93961ea0"})
  if camping_host_description is not None: camping.append(camping_host_description.text.strip())
  else: camping.append("No camping host description")

  # servizi =================================================================================================================================
  facilities_list = soup_general_data.find_all("div", {"class": "hotel-facilities-group"}) # prendo tutti i div con i servizi

  servizi_appoggio = []
  for facility in facilities_list:

    facility_title = facility.find("div", {"class": "bui-title__text hotel-facilities-group__title-text"})
    servizi_appoggio.append(facility_title.text.strip().upper())

    servizi_appoggio.append(": ")

    facility_attributes = facility.find_all("div", {"class": "bui-list__description"})
    for a in facility_attributes:
      servizi_appoggio.append(a.text.strip())
      servizi_appoggio.append(", ")
    
    servizi_appoggio.append("| ")
  
  servizi = ''.join(map(str, servizi_appoggio)) # dalla lista creo una stringa formattata cosi: SERVIZIO: attributo, attributo, attributo, | SERVIZIO: attr...
  
  camping.append(servizi)
  camping.append(l.partition("?")[0])

  camping_general_data.append(camping)


# RECENSIONI ==========================================================================================================================================
# estrapolo tutti gli url delle recensioni dei camping
all_review_urls = []
for l in links_for_reviews:

  response = requests.get(l, headers = head)
  soup = bs(response.text, 'lxml')

  n_reviews_page = getReviewsPage(soup)
  all_review_urls.append(getReviewsUrl(l, n_reviews_page)) # prendo tutti gli url contenenti recensioni

# estrapolo tutte le recensioni da tutti gli url
all_reviews = []
for list_of_url in all_review_urls:
  for url in list_of_url:
    
    response_review = requests.get(url, headers = head)
    soup_review = bs(response_review.text, 'lxml')

    print("scrape recensioni: " + url)
    all_reviews.append(getReviewsData(soup_review, url))

all_camping_reviews = []
for review_list in all_reviews:
  for review in review_list:
    all_camping_reviews.append(review)


# scrittura files
columns = ["camping_name", "camping_address", "camping_description", "camping_host_description", "camping_facilities", "url"]
general_data_dataset = pd.DataFrame(camping_general_data, columns = columns)
general_data_dataset.to_excel('C:/Users/Simo/Desktop/bda_locale/datasets/general_data_dataset.xlsx')

columns = ["reviews_vote", "reviews_title", "reviews_negative", "reviews_positive", "review_staydate", "url"]
review_dataset = pd.DataFrame(all_camping_reviews, columns = columns)
review_dataset.to_excel('C:/Users/Simo/Desktop/bda_locale/datasets/review_dataset.xlsx')