# -*- coding: utf-8 -*-
"""[booking] scraping prezzi e disponibilita'

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lhaaQO-xPQ4aodgUwLvW84g2oSZfK1Oj

"""

import requests # libreria per generare richieste HTTP 
from bs4 import BeautifulSoup as bs # libreria per scraping
import pandas as pd

def aggiungiFiltriTemporali(target_str_ ,checkin_, checkout_):

  target_str = str(target_str_)
  checkin_date = str(checkin_)
  checkout_date = str(checkout_)
  
  link_with_date = f'{target_str}?checkin={checkin_date};checkout={checkout_date};selected_currency=EUR'

  return link_with_date

# conversione a stringa e trimming dei link
def editaLinks(all_soup_href, checkin_, checkout_):

  edited_links = []
  i = 0
  while i < len(all_soup_href):
    edited_links.append(str(all_soup_href[i])) # converte i link da tipo bs4 in tipo stringa e li mette in edited_links
    edited_links[i] = edited_links[i][53:] # trimma i primi 53 caratteri
    edited_links[i] = edited_links[i].partition("?")[0] # separa in base al "?" e seleziona tutti i caratteri prima di "?"
    edited_links[i] = aggiungiFiltriTemporali(edited_links[i], checkin_, checkout_) # aggiunge le date
    i += 1

  return edited_links

# qui si interroga booking per prendere tutti i link dei camping presenti nelle Marche
url = "https://www.booking.com/searchresults.it.html?ss=Marche%2C+Italia&is_ski_area=&checkin_year=&checkin_month=&checkout_year=&checkout_month=&group_adults=2&group_children=0&no_rooms=1&b_h4u_keep_filters=&from_sf=1&dest_id=905&dest_type=region&search_selected=true&nflt=ht_id%3D224%3Bht_id%3D214"
head = {'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:100.0) Gecko/20100101 Firefox/100.0'}
response_links = requests.get(url, headers = head)
soup_links = bs(response_links.text, 'lxml')

all_links = soup_links.find_all("a", {"data-testid": "title-link"})

# qui i link vengono preparati per fare scraping dei dati dei camping, 
# vengono effettuate operazioni di trimming e vengono inseriti i periodi temporali
checkin_date = "2022-09-17"
checkout_date = "2022-09-24"
links_con_date = editaLinks(all_links, checkin_date, checkout_date)


"""**SCRAPING DATI DAI CAMPING TROVATI**"""
availability = []

for l in links_con_date:

  response = requests.get(l, headers = head)
  soup = bs(response.text, 'lxml')

  available_rooms = soup.find("div", {"id": "available_rooms"})
  hprt_table_column = available_rooms.find("div", {"class": "hprt-table-column"})

  if hprt_table_column is not None: # controlla se è presente la tabella delle disponibilità

    tbody = hprt_table_column.find('tbody')
    all_tr = tbody.find_all('tr')


    type_found = False

    for row in all_tr:
      table_row = []

      if not type_found:
        room_type = row.find("span", {"class": "hprt-roomtype-icon-link"})
        if room_type is not None:
          room_type = room_type.text.strip()
          type_found = True
      
      n_guests = row.find("div", {"class": "hprt-occupancy-occupancy-info"})
      if n_guests is not None:
        n_guests = n_guests.text.strip()
        n_guests = [int(s) for s in n_guests.split() if s.isdigit()][0]

      discount_price = row.find("div", {"class": "bui-f-color-destructive js-strikethrough-price prco-inline-block-maker-helper bui-price-display__original"})
      if discount_price is not None: discount_price = discount_price.text.strip()

      full_price = row.find("span", {"class": "prco-valign-middle-helper"})
      if full_price is not None: full_price = full_price.text.strip()

      table_row.append(room_type); table_row.append(n_guests); table_row.append(discount_price); table_row.append(full_price); table_row.append(l)
      availability.append(table_row)

      if "hprt-table-last-row" in row['class']: type_found = False

  print(">>> CAMPING: " + l)

# genera il dataset
availability_dataset = pd.DataFrame(availability, columns = ["tipologia_stanza", "numero_persone", "prezzo_pieno", "prezzo_scontato", "URL"])

OUTPUT_PATH = f'C:/Users/Simo/Desktop/bda_locale/datasets/availability_dataset_{checkin_date}_{checkout_date}.xlsx'
availability_dataset.to_excel(OUTPUT_PATH)